;;;
;;; Screen control vars for the Commander 16 Assembly Language Environment
;;;
;;; Copyright 2020 Michael J. Allison
;;; License, 2-clause BSD, see license.txt in source package.
;;; 

	.ifndef __X16_SCREEN_VARS__
	__X16_SCREEN_VARS__=1

	.import orig_color, input_string_length, input_string, input_string_cursor
	.import screen_width, screen_height, screen_row_prompt, screen_row_data_count, screen_last_row 
	.import print_to_file
	
	.endif
