;
; low level graphics
;
GRAPH_LL_init                = $fef9
GRAPH_LL_get_info            = $fefc
GRAPH_LL_cursor_position     = $feff
GRAPH_LL_cursor_next_line    = $ff02
GRAPH_LL_get_pixel           = $ff05
GRAPH_LL_get_pixels          = $ff08
GRAPH_LL_set_pixel           = $ff0b
GRAPH_LL_set_pixels          = $ff0e
GRAPH_LL_set_8_pixels        = $ff11
GRAPH_LL_set_8_pixels_opaque = $ff14
GRAPH_LL_fill_pixels         = $ff17
GRAPH_LL_filter_pixels       = $ff1a
GRAPH_LL_move_pixels         = $ff1d

