; This exposes some font symbols from KERNAL to GEOS.
; No other code should use these symbols.

k_curIndexTable         = $8e
k_baselineOffset        = $0297
k_curSetWidth           = $0298
k_curHeight             = $029a
k_cardDataPntr          = $029b
k_currentMode           = $029d
k_windowTop             = $029e
k_windowBottom          = $02a0
k_leftMargin            = $02a2
k_rightMargin           = $02a4

k_fontTemp1             = $02a6
k_fontTemp2             = $02ae
k_PrvCharWidth          = $02b7
k_FontTVar1             = $02b8
k_FontTVar2             = $02b9
k_FontTVar3             = $02bb
k_FontTVar4             = $02bc
