;
; framebuffer driver
;
FB_init                = $fef6
FB_get_info            = $fef9
FB_set_palette         = $fefc
FB_cursor_position     = $feff
FB_cursor_next_line    = $ff02
FB_get_pixel           = $ff05
FB_get_pixels          = $ff08
FB_set_pixel           = $ff0b
FB_set_pixels          = $ff0e
FB_set_8_pixels        = $ff11
FB_set_8_pixels_opaque = $ff14
FB_fill_pixels         = $ff17
FB_filter_pixels       = $ff1a
FB_move_pixels         = $ff1d

