; values of currentMode
; bit numbers
UNDERLINE_BIT           =       7
BOLD_BIT                =       6
REVERSE_BIT             =       5
ITALIC_BIT              =       4
OUTLINE_BIT             =       3
SUPERSCRIPT_BIT         =       2
SUBSCRIPT_BIT           =       1
; masks
SET_UNDERLINE           =       %10000000
SET_BOLD                =       %01000000
SET_REVERSE             =       %00100000
SET_ITALIC              =       %00010000
SET_OUTLINE             =       %00001000
SET_SUPERSCRIPT         =       %00000100
SET_SUBSCRIPT           =       %00000010
SET_PLAINTEXT           =       %00000000

; screen
SC_PIX_HEIGHT           =       200
SC_PIX_WIDTH            =       320
