; This exposes some font symbols from KERNAL to GEOS.
; No other code should use these symbols.

k_curIndexTable = $8e
k_baselineOffset = $0295
k_curSetWidth = $0296
k_curHeight = $0298
k_cardDataPntr = $0299
k_currentMode = $029b
k_windowTop = $029c
k_windowBottom = $029e
k_leftMargin = $02a0
k_rightMargin = $02a2

k_fontTemp1 = $02a4
k_fontTemp2 = $02ac
k_PrvCharWidth = $02b5
k_FontTVar1 = $02b6
k_FontTVar2 = $02b7
k_FontTVar3 = $02b9
k_FontTVar4 = $02ba

