name: ROM Build CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Install Dependencnies
        run: |
          sudo apt-get install -y make build-essential
          git clone https://github.com/cc65/cc65.git
          cd cc65
          make -j4
          sudo make install
      - name: Build ROM
        run: make
      - name: Archive firmwares results
        uses: actions/upload-artifact@v3
        with:
          name: ROM Image
          path: build/x16/